import { Bree_Serif } from "next/font/google";
import "./globals.css";

const breeSerif = Bree_Serif({
  variable: "--font-Bree-Serif",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body className={breeSerif.className}>{children}</body>
    </html>
  );
}
